### ISSUE TITLE
rebuildctl: smarter endpoint detection?

### ISSUE THREAD

**Issue by seankhliao** [kpcyrd/rebuilderd#11]
`rebuildctl` should look at `/etc/rebuilderd.conf` for finding an endpoint before falling back to the hardcoded `http://127.0.0.1:8080`. Currently it only checks the `-H` arg and a config file in the user's config directory

also would be nice to have `endpoint` under `[http]` in the default/example config for discoverability

**Comment by kpcyrd** [comment]
Good point, this has been implimented in the v0.3.0 release! Also note that the default port changed from :8080 to :8484.

**Comment by kpcyrd** [comment]
btw, in case your rebuilder is public, feel free to add it to https://wiki.archlinux.org/index.php/Package_rebuilders and/or https://github.com/kpcyrd/ismyarchverifiedyet/blob/master/ismyarchverifiedyet.py :)

**Comment by seankhliao** [comment]
I've listed a status page in the wiki page (only have access to my current hardware for a few more months), though I made the dubious decision to include all of community in my rebuilds and core seems to be stuck after it, so it might be a while before the numbers look right.

Is parallelism a thing with rebuilderd? It's running on an 8 core machine and doesn't appear to be taking full advantage of it

**Comment by kpcyrd** [comment]
There's a patch that landed recently but isn't released yet: https://github.com/archlinux/archlinux-repro/commit/63b43679b4fb73ef9492fcc0f8fe5699738ba183

You can try to apply it manually to make use of all cores.

Also, nice dashboard!

**Comment by kpcyrd** [comment]
The patch has been shipped in `archlinux-repro 20200427-1` :tada:
