### ISSUE TITLE
Signed rebuild attestations

### ISSUE THREAD

**Issue by kpcyrd** [kpcyrd/rebuilderd#12]
Right now rebuilders are very informal. They report their status, but a GOOD attestation is not used for anything serious yet. Right now it's sufficient to use the basic security that https provides.

I'm opening this as a tracking issue to collect ideas and thoughts how this should look like in the future.

**Comment by tarcieri** [comment]
You might take a look at [in-toto](https://in-toto.io/) as a metadata format for this information:

https://github.com/in-toto/docs/blob/v0.9/in-toto-spec.md

**Comment by kpcyrd** [comment]
This was implemented on 0.14.0 a while ago! :tada:
