### ISSUE TITLE
Add `make install` target

### ISSUE THREAD

**Issue by kpcyrd** [kpcyrd/rebuilderd#120]

**Comment by adityasaky** [comment]
This would be great for https://r-b.engineering.nyu.edu! One thing I'd like to see (I don't know what's default) is not overwriting the configuration files. Could it be something like what pacman does for mirrorlist updates (.pacnew)?

**Comment by kpcyrd** [comment]
@adityasaky that should already be the case in the latest Arch Linux package:

```sh
  pkgdesc='Independent verification system of binary packages (server package)'
  depends=('rebuilderd-tools' 'sqlite' 'archlinux-repro')
  backup=('etc/rebuilderd.conf'
          'etc/rebuilderd-sync.conf'
          'etc/rebuilderd-worker.conf')
```
https://github.com/archlinux/svntogit-community/blob/436272579b4d9a48b1af696a90746905f11ddc1a/trunk/PKGBUILD#L41-L43

Does this still occur for you? This should be considered in the `make install` target though, yes. :)

**Comment by adityasaky** [comment]
Nice! The NYU rebuilder doesn't run on Arch, so I build and install manually from source.
