### ISSUE TITLE
rebuildctl should be more verbose when encountering issues

### ISSUE THREAD

**Issue by h01ger** [kpcyrd/rebuilderd#155]
So (currently) I run this command in a loop:

 while true ; do env REBUILDERD_COOKIE_PATH=~/.local/share/rebuilderd-auth-cookie /opt/usr/bin/rebuildctl -H http://127.0.0.1:8484 pkgs sync-profile --sync-config /opt/etc/rebuilderd-sync.conf debian-main ; echo sleeping 3h now ; sleep 3h ; done

and get this output every 3h:

```
[2024-11-27T12:25:36Z INFO  rebuildctl::schedule] Downloading "http://deb.debian.org/debian/dists/sid/main/source/Sources.xz"...
[2024-11-27T12:25:37Z INFO  rebuildctl::schedule::debian] Building map of all source packages
[2024-11-27T12:25:39Z INFO  rebuildctl::schedule] Downloading "http://deb.debian.org/debian/dists/sid/main/binary-amd64/Packages.xz"...
Error: No source package found with name: "buildlog-consultant"
```

and now we are wondering: does this error cause the scheduling to end or is that package just skipped?

suggestion: append "skipping pkg" or "aborting" to the output, so that it becomes either

Error: No source package found with name: "buildlog-consultant", aborting.

or

Error: No source package found with name: "buildlog-consultant", skipping package and continueing.

background: buildlog-consultant was removed from unstable, but appearantly it's binary packages survived: (which obviously is a bug in ftp.d.o)

```
$ rmadison buildlog-consultant
 buildlog-consultant | 0.0.21-1    | bookworm | source
 buildlog-consultant | 0.0.44-1+b1 | sid      | amd64, arm64, armel, armhf, i386, mips64el, ppc64el, riscv64, s390x
```

I fear such situation might happen again.

**Comment by h01ger** [comment]
just confirmed: the scheduling is aborted, we have no new packages scheduled since november 19th when buildlog-consultant was partly removed.

please a.) skip this such broken packages and explain doing so and b.) continue scheduling other packages.

**Comment by cjwatson** [comment]
The `buildlog-consultant` binaries in unstable are not sourceless:

```
$ rmadison -S rust-buildlog-consultant
buildlog-consultant             | 0.0.44-1+b1   | unstable       | amd64, arm64, armel, armhf, i386, mips64el, ppc64el, riscv64, s390x
buildlog-consultant-dbgsym      | 0.0.44-1+b1   | unstable-debug | amd64, arm64, armel, armhf, i386, mips64el, ppc64el, riscv64, s390x
librust-buildlog-consultant-dev | 0.0.44-1+b1   | unstable       | amd64, arm64, armel, armhf, i386, mips64el, ppc64el, riscv64, s390x
rust-buildlog-consultant        | 0.0.44-1      | unstable       | source
rust-buildlog-consultant        | 0.0.44-1      | unstable-debug | source
rust-buildlog-consultant        | 0.1.0-1       | unstable       | source
```
