### ISSUE TITLE
store last modification in JSON output

### ISSUE THREAD

**Issue by aparcar** [kpcyrd/rebuilderd#18]
I'm trying to store the generated files in a database, for that it would be important to know the latest modification. Please offer the date of last change as a unix timestamp, e.g. `build_date`.

**Comment by kpcyrd** [comment]
Would it be sufficient to attach the build date to each package?

**Comment by aparcar** [comment]
Ideally the API would use the lasts-modified header so the file is only downloaded when something changed. Having it per result would require do download and parse the file every time.

**Comment by kpcyrd** [comment]
There are no files, the response by /api/v0/pkgs/list is generated on the fly :)

**Comment by aparcar** [comment]
Depending on the framework you're using to offer the file you can often add custom headers, like the modification one.

I'm not familiar enough with rust to do so, but please add the package specific build dates and then I'll create a PR adding the header.
