### ISSUE TITLE
rebuilderd-worker@.service: all builds fail

### ISSUE THREAD

**Issue by stefan0xC** [kpcyrd/rebuilderd#28]
Due to the introduction of `setsid -c` in repro (cf. archlinux/archlinux-repro#82 ) and that by [default](https://www.freedesktop.org/software/systemd/man/systemd.exec.html) systemd-services don't run in a terminal, by running rebuilderd-worker@build.service all builds will eventually fail with the following message: 

    setsid: failed to set the controlling terminal: Inappropriate ioctl for device

I am not sure if this issue can be resolved by simply telling the service to use a tty somehow. As far as I've tested it this results in the referenced bug (ie. first build succeeding, subsequent failing until service is restarted).

**Comment by kpcyrd** [comment]
hey! I've opened a PR in archlinux-repro to apply a patch that has been floating around for a while. I'm not sure if there's a better way to work around this unfortunately, but I'd be very interested if there is one!

**Comment by kpcyrd** [comment]
The patch was merged, keeping this issue open until a new repro version was released.
