### ISSUE TITLE
Support a build timeout for "stuck" builds

### ISSUE THREAD

**Issue by jelly** [kpcyrd/rebuilderd#6]
Some rebuilds will get stuck due to build issues which seem to hang the build forever such as GCC, implementing a build timeout which kills the build and marks it as bad. Otherwise a whole worker is blocked as it seems that restarting the worker will pick up the task again. It's hard to found a good kill timeout since builds may take arbitrary time due to hardware or network limitations so it might be a good thing to be able to configure the timeout in rebuilderd-worker.conf

```
Apr 24 14:25:45 repro2.pkgbuild.com rebuilderd-worker[972844]: make[4]: Entering directory '/build/gcc/src/gcc-build/build-x86_64-pc-linux-gnu/libiberty/testsuite'
Apr 24 14:25:45 repro2.pkgbuild.com rebuilderd-worker[972844]: make[4]: Nothing to be done for 'all'.
Apr 24 14:25:45 repro2.pkgbuild.com rebuilderd-worker[972844]: make[4]: Leaving directory '/build/gcc/src/gcc-build/build-x86_64-pc-linux-gnu/libiberty/testsuite'
Apr 24 14:26:01 repro2.pkgbuild.com rebuilderd-worker[978109]: checking whether objcopy supports debuglink...
Apr 24 14:26:01 repro2.pkgbuild.com rebuilderd-worker[978109]: bjcopy: /tmp/ls33612: cannot fill deb
```

**Comment by kpcyrd** [comment]
This is currently solved with a hard-coded 1d timeout
