### ISSUE TITLE
Add support for other compression formats for the repository database

### ISSUE THREAD

**Issue by adityasaky** [kpcyrd/rebuilderd#61]
`rebuilderd` currently supports only gzip compression for the Arch Linux `repo.db` file. We ran into this issue on our mirror because we use `.tar.xz` files rather than `.tar.gz`. We've switched to `.tar.gz` now. However, since pacman's `repo-add` supports a variety of formats, I imagine this can be a problem going forward for other folks.

**Comment by kpcyrd** [comment]
Thanks for reporting, this is going to be fixed in the next release!
